Repository openshift/cluster-support-bot, pull requests merged in 2019-11, with the labels that each got.

#18 proactive-support-bot: Hydra integration for summary/comments
  README.md
  hydra.py
  proactive-support-bot.py
Labels: size/L

#17 cluster-support-bot: Rebranding
  README.md
  cluster-support-bot.py
Labels: size/S

#19 README: Shuffle docs and add more detailed workflow notes
  CONTRIBUTING.md
  LICENSE
  README.md
  cluster-support-bot.py
  install.md
Labels: size/L

#20 hydra: Truncate long error responses
  hydra.py
Labels: size/XS

#21 slack api: port from Slack Events API to Slack RTM API
  cluster-support-bot.py
  install.md
  requirements.txt
Labels: size/L

#13 telemetry: Add EBS-account lookup via subscription_labels
  README.md
  cluster-support-bot.py
  errors.py
  hydra.py
  install.md
  telemetry.py
Labels: size/L

#22 cluster-support-bot: Include dashboard URI regardless of summary note
  cluster-support-bot.py
Labels: size/XS

#23 cluster-support-bot: Expose subscription managed and support values
  cluster-support-bot.py
  telemetry.py
Labels: size/M

#27 README: 'cluster-support-bot' -> 'cluster-support'
  CONTRIBUTING.md
  README.md
Labels: size/S

#25 cluster-support-bot: Mention related open cases in the summary
  cluster-support-bot.py
  hydra.py
Labels: size/S

#32 cluster-support-bot: Add entitlements
  cluster-support-bot.py
  hydra.py
Labels: size/S

#31 First pass at promentheus endpoint for Issue #28
  cluster-support-bot.py
  install.md
  requirements.txt
Labels: size/M
